# .github/workflows/deploy.yml

name: CI/CD Pipeline for AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda-functions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [AuthenticateFunction, GetPageInfoFunction, AddPageInfoFunction]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd ${{ matrix.function }}
          npm install

      - name: Zip Function
        run: |
          cd ${{ matrix.function }}
          zip -r function.zip ./*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.function }} \
            --zip-file fileb://${{ matrix.function }}/function.zip

      - name: Clean Up Zip File
        run: |
          cd ${{ matrix.function }}
          rm function.zip
